# These are supported funding model platforms

github: [afzalimdad9]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: [afzalimdad9]# Replace with a single Patreon username
buy_me_a_coffee: [afzalimdad9]# Replace with a single Buy Me a Coffee username
